### ISSUE TITLE
uploading issue

### ISSUE THREAD

**Issue by Linus789** [EliuX/MEGAcmd4J#10]
```
Exception in thread "main" io.github.eliux.mega.error.MegaUnexpectedFailureException: Unexpected failure with code 21
	at io.github.eliux.mega.MegaUtils.handleResult(MegaUtils.java:66)
	at io.github.eliux.mega.cmd.AbstractMegaCmdRunner.executeSysCmd(AbstractMegaCmdRunner.java:20)
	at io.github.eliux.mega.cmd.AbstractMegaCmdRunnerWithParams.run(AbstractMegaCmdRunnerWithParams.java:8)
```

```
class MEGA(_file: File) {

    private val file: File = _file

    fun upload(): String {
        val sessionMega: MegaSession = try {
            Mega.currentSession()
        } catch (e: MegaException) {
            Mega.login(MegaAuthCredentials(MAIL, PASSWORD))
        }

        sessionMega.uploadFile(file.canonicalPath, "test/").run() // ERROR HERE (dir "test" exists)
        return sessionMega.export("test/${file.name}").call().publicLink
    }

}
```

Upload doesn't work, creating directories does work.
Using Linux Mint 18, MegaCMD installed.
Thanks in advance ^^

**Comment by Linus789** [comment]
```
Exception in thread "main" io.github.eliux.mega.error.MegaUnexpectedFailureException: Unexpected failure with code 2
	at io.github.eliux.mega.MegaUtils.handleResult(MegaUtils.java:66)
	at io.github.eliux.mega.cmd.AbstractMegaCmdRunner.executeSysCmd(AbstractMegaCmdRunner.java:20)
	at io.github.eliux.mega.cmd.AbstractMegaCmdRunnerWithParams.run(AbstractMegaCmdRunnerWithParams.java:8)
```
changed to `sessionMega.uploadFile("\"${file.canonicalPath}\"", "/")` because there were whitespaces in the path, but now there's another error code.

**Comment by Linus789** [comment]
I changed it to `sessionMega.uploadFile(file.path, "/").run()` and it works now
but it's strange that the other way it didn't

**Comment by EliuX** [comment]
Hi @Linus789, thanks for posting your feedback. I checked your code. 
## Short answer
By design, you cannot upload content to an unexisting Mega folder, e.g. `/test`. If you want to upload content to a folder that doesnt exist you can do it easily by including the option `createRemoteIfNotPresent`, as its shown in the [quickstart](https://github.com/EliuX/MEGAcmd4J/wiki/Quick-start#execute-commands-with-the-initiated-megasession). The other call you tried, should not work neither, because your are trying to upload a file with a path separator (`\`) at the end. Even if you want to upload a folder you should never specify a path separator at the end (I tested it and the folder and its subfolder were uploaded).
## More info
The documentation infered for every cmd command is the one of the corresponding *MEGAcmd* command. In case you want to check the documentation of the `Mega.uploadFile` you will see that it returns a `MegaCmdPutSingle` class, so it correspond to the put command (meant for just a single file). In case you doubt which command is used you can clarify it by checking the `getCmd` function of every class derived from `AbstractMegaCmd`. When you check the help for `put` with `mega-put.bat --help` (use `.sh` for Unix OSs) you should get something like:
```
$ mega-put.bat --help
Usage: put  [-c] [-q] [--ignore-quota-warn] localfile [localfile2 localfile3 ...] [dstremotepath]
Uploads files/folders to a remote folder

Options:
 -c     Creates remote folder destination in case of not existing.
 -q     queue upload: execute in the background. Don't wait for it to end'
 --ignore-quota-warn    ignore quota surpassing warning.
                          The upload will be attempted anyway.

Notice that the dstremotepath can only be omitted when only one local path is provided.
 In such case, the current remote working dir will be the destination for the upload.
 Mind that using wildcards for local paths will result in multiple paths.
```
You will see there is an option called `c` for creating a remote folder in case it doesnt exist. As `c` is not a very verbose option, `createRemoteIfNotPresent` seemed like the best possible choice.

**Comment by EliuX** [comment]
Feedbacks are great, now reviewing the code I decided to change the function `createRemoteIfNotPresent` to something like `createRemotePathIfNotPresent`, so I created an [issue ](https://github.com/EliuX/MEGAcmd4J/issues/11) for that purpose :).  Maybe I used that name just to make it shorter and less redundant; but intuitive is more important.

**Comment by EliuX** [comment]
Hi @Linus789, responding to your statements
>So, first I created the directory test manually, so there should be no problem.
I tried the following code, inspired in yours, having created a `test` folder in my Mega account and it worked without problem:
```java
package com.eliux.sample;

import io.github.eliux.mega.Mega;
import io.github.eliux.mega.MegaSession;

import java.io.File;
import java.io.IOException;

public class MEGA {

    private File _file;

    public static void main(String... args) {
        File file = new File(args[0]);
        try {
            String uploadedFilePublicLink = upload(file);
            System.out.printf("You can access the file with '%s'", uploadedFilePublicLink);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static String upload(File file) throws IOException {
        final MegaSession sessionMega = Mega.init();
        sessionMega.uploadFile(file.getCanonicalPath(), "test/").run();
        return sessionMega.export("test/" + file.getName())
                .call()
                .getPublicLink();
    }
}
```
> I used the quotes for specifying a path with whitespaces, example:
/home/linus/path with whitespace/test/file.txt
I hoped, that it would work. But it didn't. In the end, I used sessionMega.uploadFile(file.path, "/").run(). Perhaps it worked because file.path returns the relative path without whitespaces. Example: test/file.txt

Based on what you tell me I did some tests with the `mega-put` command, and Yes, you are right, it needs path must be specified between `"` to make it work with whitespaces in the path, e.g.
```
mega-put.bat -c "<root path>\folder with spaces\my_text_files.txt" "test/folder with spaces/"
``` 
I created an [issue ](https://github.com/EliuX/MEGAcmd4J/issues/13) to handle this particular problem.

**Comment by Linus789** [comment]
But in order to upload from a path with whitespaces I used these quotes:
`sessionMega.uploadFile("\"${file.canonicalPath}\"", "/")`

But it didn't work, though it worked in the console with `mega-put`. That's strange.

**Comment by EliuX** [comment]
Checkout the latest release, where I solve this issue
```
<dependency>
  <groupId>com.github.eliux</groupId>
  <artifactId>megacmd4j</artifactId>
  <version>1.3.0</version>
</dependency>
```
If you dont see it solved, please re-open this issue again.
