### ISSUE TITLE
i have a problème how i can download a public link with Megacmd 

### ISSUE THREAD

**Issue by Virusreadme** [EliuX/MEGAcmd4J#21]
ihave this message : is not a valid Download Folder

Please help me

**Comment by ccenyo** [comment]
Do you want to download to your local computer or to your cloud?

**Comment by EliuX** [comment]
Hi @Virusreadme please try to provide more information about the issue you are having. I am really out of context here :)

**Comment by EliuX** [comment]
Ok, I will suppose that you want to download a remote file or folder in your Mega.nz account into an existing local path. Then you just have to use the `get` command. Check out this test:

```
    sessionMega.get("remotefolder/folderwithfiles", "targetlocalfolder")
        .run();

    assertTrue(
        new File("targetlocalfolder/folderwithfiles").isDirectory(),
        "Invalid downloaded directory"
    );
    assertTrue(
        new File("targetlocalfolder/folderwithfiles/yolo.txt").isFile(),
        "Invalid downloaded file"
    );
```

If the local path doesnt exist then you will get a `MegaInvalidTypeException`.  Maybe the error you are having is because of that.


To check out basic scenarios I would recommend you to check out `io.github.eliux.mega.cmd.BasicActionsTest`
